Addition: Instagram recent pics and video downloader
yashshah1/Instagram-Hacks pull request #3
Opened 2020-10-01 18:54 UTC by kartikmandhan

This Instagram images and video downloader works for public accounts and downloads images and videos of that account

2020-10-02 10:08 UTC, yashshah1 requested changes
Add all the downloaded videos into a new folder, which can probably be named the time of the script execution

2020-10-02 10:08 UTC, yashshah1 commented on comment_on_all_photos/src.py
> +login = driver.find_element_by_xpath('//*[@id="loginForm"]/div/div[3]')
This is from another commit, please merge from upstream

2020-10-02 10:08 UTC, yashshah1 commented on recent_image_and_pic_downloader/src.py
> +from selenium import webdriver
```suggestion
import time
import requests
from selenium import webdriver
```

Avoid unnecessary newlines

2020-10-03 10:54 UTC, kartikmandhan reviewed
i have made all the desired changes

2020-10-03 10:55 UTC, kartikmandhan reviewed
directory structure created for video and image files

2020-10-03 14:14 UTC, merged